on:
  push:
    branches:
      - main
env:
  GAR_LOCATION: asia-northeast3-docker.pkg.dev
  PROJECT_ID: dev-pasta
  REPOSITORY: img-dev-pasta-api
  IMAGE: application
  SERVICE: run-dev-pasta-api
  REGION: asia-northeast3
  PROFILE: dev
  API_URL: https://com-api.kakaohealthcare.com/api/ext/deploy/
  PROJECT: vc
  REPO_URL: https://github.com/${GITHUB_REPOSITORY}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Gitlab Pipeline Trigger
        run: |
          curl -X POST \
              --fail \
              -H "Content-Type: application/json" \
              -H "Authorization: [{"key":"Authorization","value":"Token e7fc6a628e99d2714ad617a7aaf092db4505d601","description":"","type":"text","enabled":true,"uuid":"28cf3c84-6741-4a84-9e8d-46d1f9a73f83"}]" \
              -d '{
                    "profile": "'"${PROFILE}"'",
                    "project": "'"${PROJECT}"'",
                    "branch": "'"${GITHUB_REF_NAME}"'",
                    "repo": "'"${{ github.event.repository.name }}"'",
                    "repo_url": "'"${REPO_URL}"'",
                    "username": "'"${GITHUB_ACTOR}"'"
                  }' \
              ${API_URL}
