name: Deploy to GCP dev Manually

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  GAR_LOCATION: asia-northeast3-docker.pkg.dev
  PROJECT_ID: dev-pasta
  REPOSITORY: img-dev-pasta-webview
  IMAGE: application
  SERVICE: run-dev-pasta-webview
  REGION: asia-northeast3
  PROFILE: dev
  PROJECT: vc
  APPLICATION: webview
  BUILD: node
  TOKEN: e7fc6a628e99d2714ad617a7aaf092db4505d601
  API_URL: https://com-api.kakaohealthcare.com/api/ext/deploy/
  COMMIT_ID: default
  COMMIT_MESSAGE: default

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Gitlab Pipeline Trigger
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          COMMIT_MESSAGE=$(git log -1 --pretty=%B | sed -n -e '1p' | awk '{printf "%s\\n", $0}' | sed 's/"/\\"/g')
          curl -X POST \
              --fail \
              -H "Content-Type: application/json" \
              -H "Authorization: Token ${TOKEN}" \
              -d '{
                    "profile": "'"${PROFILE}"'",
                    "project": "'"${PROJECT}"'",
                    "application": "'"${APPLICATION}"'",
                    "branch": "'"${GITHUB_REF_NAME}"'",
                    "repo": "'"pasta-webview"'",
                    "repo_url": "'"https://github.com/${GITHUB_REPOSITORY}"'",
                    "username": "'"${GITHUB_ACTOR}"'",
                    "commit_msg": "'"${COMMIT_MESSAGE}"'",
                    "build": "'"${BUILD}"'",
                    "commit_id": "'"${COMMIT_ID}"'"
                  }' \
              ${API_URL}




              
