name: deploy api (Gitlab TEST)

on:
  workflow_dispatch:

env:
  PROFILE: dev
  PROJECT: vc
  APPLICATION: api
  BUILD: java
  API_URL: https://com-api.kakaohealthcare.com/api/ext/deploy/
  TOKEN: e7fc6a628e99d2714ad617a7aaf092db4505d601
  COMMIT_ID: aaa
  COMMIT_MESSAGE: bbb
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Gitlab Pipeline Trigger
        run: |          
          echo "'"${PROFILE}"'"
