name: Python application

on:
  push:
    branches:
      - main

env:
  GAR_LOCATION: asia-northeast3-docker.pkg.dev
  PROJECT_ID: dev-pasta
  REPOSITORY: img-dev-pasta-api
  IMAGE: application
  SERVICE: run-dev-pasta-api
  REGION: asia-northeast3
  PROFILE: dev
  GITLAB: https://com-khclab.kakaohealthcare.com/api/v4/projects/795/trigger/pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Gitlab Pipeline Trigger
        run: |
          curl -X POST \
              --fail \
              -F token=551b505bcffa486dba2a9a3b1f1ae7 \
              -F ref=main \
              -F "variables[PROFILE]=${PROFILE}" \
              ${GITLAB}