name: deploy api (Gitlab TEST)

on:
  workflow_dispatch:

env:
  PROFILE: dev
  PROJECT: vc
  APPLICATION: api
  BUILD: java
  API_URL: https://com-api.kakaohealthcare.com/api/ext/deploy/
  TOKEN: ${{ secrets.INFRA_TOKEN }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Gitlab Pipeline Trigger
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          curl -X POST \
              --fail \
              -H "Content-Type: application/json" \
              -H "Authorization: Token ${TOKEN}" \
              -d '{
                    "profile": "'"${PROFILE}"'",
                    "project": "'"${PROJECT}"'",
                    "application": "'"${APPLICATION}"'",
                    "branch": "'"${GITHUB_REF_NAME}"'",
                    "repo": "'"${{ github.event.repository.name }}"'",
                    "repo_url": "'"https://github.com/${GITHUB_REPOSITORY}"'",
                    "username": "'"${GITHUB_ACTOR}"'",
                    "commit_msg": "'"${COMMIT_MESSAGE}"'",
                    "build": "'"${BUILD}"'",
                    "commit_id": "'"${COMMIT_ID}"'"
                  }' \
              ${API_URL}
