on:
  push:
    branches:
      - main
env:
  PROFILE: dev
  PROJECT: vc
  APPLICATION: api
  BUILD_LANG: java
  API_URL: https://com-api.kakaohealthcare.com/api/ext/deploy/
  TOKEN: ${{ secrets.INFRA_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Gitlab Pipeline Trigger
        run: |
          curl -X POST \
              --fail \
              -H "Content-Type: application/json" \
              -H "Authorization: Token ${TOKEN}" \
              -d '{
                    "profile": "'"${PROFILE}"'",
                    "project": "'"${PROJECT}"'",
                    "application": "'"${APPLICATION}"'",
                    "branch": "'"${GITHUB_REF_NAME}"'",
                    "repo": "'"${{ github.event.repository.name }}"'",
                    "repo_url": "'"http://github.com/${GITHUB_REPOSITORY}"'",
                    "username": "'"${GITHUB_ACTOR}"'",
                    "commit_msg": "'"${{ github.event.head_commit.message }}"'",
                    "build": "'"${{ BUILD_LANG }}"'",
                    "commit_id": "'"${{ github.event.head_commit.id }}"'"
                  }' \
              ${API_URL}
